export const TODA_LIST = [
  // CLUSTER 1
  "SINGPECCK SINGALAT TODA INC.",
  "BARANGAY MARCOS VILLAGE TODA INC.",
  "ATATE BLISS CAMPFARM TRI-MOVERS TODA INC.",
  "PROGRESSIVE ATATE TRICYCLE OPERATORS AND DRIVERS ASSOCIATION INC.",
  "BARANGAY SAPANG BUHO TRI-MOVERS TODA INC.",
  "SALUPUNGAN PALAYAN BONGABON LAUR TODA INC.",
  // CLUSTER 2
  "BARANGAY CAIMITO PUBLIC MARKET TRI-MOVERS TODA INC.",
  "BARANGAY MALATE POBLACION TRI-MOVERS TODA INC.",
  "DAOPP TODA ASSOCIATION INC.",
  "CAIMITO HOSPITAL TRI-MOVERS TODA INC.",
  "BRGY. GANADERIA PLAZA POBLACION TODA TRI-MOVERS INC.",
  "BARANGAY SANTOLAN PALAYAN CITY COMMUNITY TODA INC.",
  "BARANGAY MALATE CENTRO TRI-MOVERS TODA INC.",
  "CABALLERO POBLACION PALAYAN TODA INC.",
  // CLUSTER 3
  "BARANGAY MANACNAC PALAYAN CITY TODA INC.",
  "A. MANGGAHAN TRICYCLE OPERATORS & DRIVERS ASSN. INC.",
  // CLUSTER 4
  "BARANGAY MILITAR PALAYAN CITY TODA INC."
];
